// ═══════════════════════════════════════════════════════════════════════════════
// THEMATIC LESSON DATA
// ═══════════════════════════════════════════════════════════════════════════════
const THEMATIC_LESSONS = [
  {
    id: 'days-of-week',
    title: 'Μέρες της εβδομάδας',
    titleEn: 'Days of the week',
    icon: '📅',
    words: [
      { en: 'Monday', gr: 'Δευτέρα', sentence: 'Κάθε Δευτέρα πρωί λέω ότι θα πάω γυμναστήριο, αλλά τελικά πάντα καταλήγω στον καναπέ.', sentenceEn: 'Every Monday morning I say I\'ll go to the gym, but I always end up on the sofa.' },
      { en: 'Tuesday', gr: 'Τρίτη', sentence: 'Την Τρίτη έχουμε συνάντηση στη δουλειά που δεν τελειώνει ποτέ — σοβαρά, κρατάει τρεις ώρες.', sentenceEn: 'On Tuesday we have a work meeting that never ends — seriously, it lasts three hours.' },
      { en: 'Wednesday', gr: 'Τετάρτη', sentence: 'Η Τετάρτη είναι η μέρα που λέμε «ευτυχώς, πέρασε η μισή εβδομάδα», σωστά;', sentenceEn: 'Wednesday is the day we say "thankfully, half the week is over", right?' },
      { en: 'Thursday', gr: 'Πέμπτη', sentence: 'Την Πέμπτη το βράδυ ετοιμάζω τη βαλίτσα μου γιατί φεύγω για Θεσσαλονίκη το πρωί.', sentenceEn: 'On Thursday evening I pack my suitcase because I\'m leaving for Thessaloniki in the morning.' },
      { en: 'Friday', gr: 'Παρασκευή', sentence: 'Ποιος δουλεύει Παρασκευή απόγευμα; Εγώ όχι — κλείνω τον υπολογιστή στις τρεις!', sentenceEn: 'Who works on Friday afternoon? Not me — I close my laptop at three!' },
      { en: 'Saturday', gr: 'Σάββατο', sentence: 'Το Σάββατο ξυπνήσαμε στις δώδεκα και πήγαμε για μπρούντς στην παραλία.', sentenceEn: 'On Saturday we woke up at noon and went for brunch by the beach.' },
      { en: 'Sunday', gr: 'Κυριακή', sentence: 'Την Κυριακή η γιαγιά μαγειρεύει για δεκαπέντε άτομα, ακόμα κι αν είμαστε μόνο πέντε.', sentenceEn: 'On Sunday grandma cooks for fifteen people, even if there are only five of us.' },
    ],
  },
  {
    id: 'telling-time',
    title: 'Η ώρα',
    titleEn: 'Telling the time',
    icon: '🕐',
    words: [
      { en: 'What time is it?', gr: 'Τι ώρα είναι;', sentence: 'Συγγνώμη, τι ώρα είναι; Νομίζω αργώ.', sentenceEn: 'Excuse me, what time is it? I think I\'m late.' },
      { en: 'one o\'clock', gr: 'μία η ώρα', sentence: 'Είναι μία η ώρα και πεινάω.', sentenceEn: 'It\'s one o\'clock and I\'m hungry.' },
      { en: 'two o\'clock', gr: 'δύο η ώρα', sentence: 'Ελάτε στις δύο, θα είμαστε έτοιμοι.', sentenceEn: 'Come at two, we\'ll be ready.' },
      { en: 'three o\'clock', gr: 'τρεις η ώρα', sentence: 'Ποιος χτυπάει την πόρτα στις τρεις τη νύχτα;', sentenceEn: 'Who knocks on the door at three in the morning?' },
      { en: 'four o\'clock', gr: 'τέσσερις η ώρα', sentence: 'Ο καφές είναι στις τέσσερις.', sentenceEn: 'Coffee is at four o\'clock.' },
      { en: 'five o\'clock', gr: 'πέντε η ώρα', sentence: 'Στις πέντε σταματάω ό,τι κάνω και φεύγω.', sentenceEn: 'At five I stop whatever I\'m doing and leave.' },
      { en: 'six o\'clock', gr: 'έξι η ώρα', sentence: 'Το ηλιοβασίλεμα στις έξι ήταν απίστευτο.', sentenceEn: 'The sunset at six was incredible.' },
      { en: 'seven o\'clock', gr: 'εφτά η ώρα', sentence: 'Ξυπνάω στις εφτά κάθε μέρα.', sentenceEn: 'I wake up at seven every day.' },
      { en: 'eight o\'clock', gr: 'οχτώ η ώρα', sentence: 'Βιάσου, η ταινία αρχίζει στις οχτώ!', sentenceEn: 'Hurry, the movie starts at eight!' },
      { en: 'nine o\'clock', gr: 'εννιά η ώρα', sentence: 'Στις εννιά τα παιδιά πρέπει να κοιμηθούν.', sentenceEn: 'At nine the kids need to go to sleep.' },
      { en: 'ten o\'clock', gr: 'δέκα η ώρα', sentence: 'Στις δέκα κλείνει το μαγαζί.', sentenceEn: 'The shop closes at ten.' },
      { en: 'eleven o\'clock', gr: 'έντεκα η ώρα', sentence: 'Ποιος τρώει μεσημεριανό στις έντεκα;', sentenceEn: 'Who eats lunch at eleven?' },
      { en: 'twelve o\'clock', gr: 'δώδεκα η ώρα', sentence: 'Στις δώδεκα ακριβώς χτυπάει η καμπάνα.', sentenceEn: 'At exactly twelve the bell rings.' },
      { en: 'quarter past', gr: 'και τέταρτο', sentence: 'Είναι τρεις και τέταρτο, πού είσαι;', sentenceEn: 'It\'s quarter past three, where are you?' },
      { en: 'half past', gr: 'και μισή', sentence: 'Θα φτάσω στις εφτά και μισή περίπου.', sentenceEn: 'I\'ll arrive at about half past seven.' },
      { en: 'quarter to', gr: 'παρά τέταρτο', sentence: 'Φεύγουμε στις δέκα παρά τέταρτο, ετοιμάσου.', sentenceEn: 'We leave at quarter to ten, get ready.' },
      { en: 'in the morning', gr: 'το πρωί', sentence: 'Το πρωί χωρίς καφέ δεν λειτουργώ.', sentenceEn: 'In the morning without coffee I can\'t function.' },
      { en: 'in the afternoon', gr: 'το απόγευμα', sentence: 'Το απόγευμα θα πάμε μια βόλτα;', sentenceEn: 'Shall we go for a walk in the afternoon?' },
      { en: 'in the evening', gr: 'το βράδυ', sentence: 'Το βράδυ βλέπουμε ταινία.', sentenceEn: 'In the evening we watch a movie.' },
      { en: 'at midnight', gr: 'τα μεσάνυχτα', sentence: 'Τα μεσάνυχτα ο γείτονας βάζει δυνατά μουσική.', sentenceEn: 'At midnight the neighbour puts on loud music.' },
    ],
  },
  {
    id: 'restaurant-menu',
    title: 'Εστιατόριο & Καφέ',
    titleEn: 'Restaurant & cafe menu',
    icon: '🍽️',
    words: [
      { en: 'Greek salad', gr: 'χωριάτικη σαλάτα', sentence: 'Μία χωριάτικη σαλάτα χωρίς κρεμμύδι, παρακαλώ.', sentenceEn: 'One Greek salad without onion, please.' },
      { en: 'tzatziki', gr: 'τζατζίκι', sentence: 'Το τζατζίκι χρειάζεται περισσότερο σκόρδο.', sentenceEn: 'The tzatziki needs more garlic.' },
      { en: 'pita bread', gr: 'πίτα', sentence: 'Θέλω πίτα ζεστή, όχι κρύα!', sentenceEn: 'I want hot pita, not cold!' },
      { en: 'grilled meat', gr: 'ψητό κρέας', sentence: 'Η μυρωδιά από ψητό κρέας με τρελαίνει.', sentenceEn: 'The smell of grilled meat drives me crazy.' },
      { en: 'souvlaki', gr: 'σουβλάκι', sentence: 'Ένα σουβλάκι κοτόπουλο με τα πάντα.', sentenceEn: 'One chicken souvlaki with everything.' },
      { en: 'gyros', gr: 'γύρος', sentence: 'Ο γύρος στις δύο τη νύχτα είναι τελετουργία.', sentenceEn: 'Gyros at 2 AM is a ritual.' },
      { en: 'moussaka', gr: 'μουσακάς', sentence: 'Η μαμά μου φτιάχνει τον καλύτερο μουσακά.', sentenceEn: 'My mum makes the best moussaka.' },
      { en: 'stuffed vine leaves', gr: 'ντολμαδάκια', sentence: 'Τα ντολμαδάκια θέλουν λεμόνι.', sentenceEn: 'Stuffed vine leaves need lemon.' },
      { en: 'spinach pie', gr: 'σπανακόπιτα', sentence: 'Πήρα σπανακόπιτα από τον φούρνο.', sentenceEn: 'I got a spinach pie from the bakery.' },
      { en: 'cheese pie', gr: 'τυρόπιτα', sentence: 'Η τυρόπιτα είναι το τέλειο πρωινό.', sentenceEn: 'Cheese pie is the perfect breakfast.' },
      { en: 'fried cheese', gr: 'σαγανάκι', sentence: 'Σαγανάκι και μπύρα — τι άλλο θέλεις;', sentenceEn: 'Fried cheese and beer — what else do you need?' },
      { en: 'grilled octopus', gr: 'χταπόδι σχάρας', sentence: 'Το χταπόδι σχάρας είναι τρυφερό.', sentenceEn: 'The grilled octopus is tender.' },
      { en: 'calamari', gr: 'καλαμαράκια', sentence: 'Τα καλαμαράκια τηγανητά είναι τραγανά.', sentenceEn: 'The fried calamari are crispy.' },
      { en: 'shrimp', gr: 'γαρίδες', sentence: 'Θέλω γαρίδες σαγανάκι.', sentenceEn: 'I want shrimp saganaki.' },
      { en: 'fish', gr: 'ψάρι', sentence: 'Το ψάρι είναι φρέσκο σήμερα.', sentenceEn: 'The fish is fresh today.' },
      { en: 'lamb chops', gr: 'παϊδάκια', sentence: 'Τα παϊδάκια στα κάρβουνα είναι φανταστικά.', sentenceEn: 'The charcoal-grilled lamb chops are fantastic.' },
      { en: 'meatballs', gr: 'κεφτέδες', sentence: 'Η γιαγιά φτιάχνει κεφτέδες κάθε Κυριακή.', sentenceEn: 'Grandma makes meatballs every Sunday.' },
      { en: 'stuffed peppers', gr: 'γεμιστά', sentence: 'Τα γεμιστά έχουν ρύζι και ντομάτα.', sentenceEn: 'The stuffed peppers have rice and tomato.' },
      { en: 'chips / French fries', gr: 'πατάτες τηγανητές', sentence: 'Πατάτες τηγανητές δίπλα στη θάλασσα!', sentenceEn: 'French fries by the sea!' },
      { en: 'rice', gr: 'ρύζι', sentence: 'Θέλεις ρύζι ή πατάτες;', sentenceEn: 'Do you want rice or potatoes?' },
      { en: 'lentil soup', gr: 'φακές', sentence: 'Οι φακές είναι σούπερ φαγητό.', sentenceEn: 'Lentil soup is a superfood.' },
      { en: 'bean soup', gr: 'φασολάδα', sentence: 'Η φασολάδα ζεσταίνει τον χειμώνα.', sentenceEn: 'Bean soup warms the winter.' },
      { en: 'olive oil', gr: 'ελαιόλαδο', sentence: 'Βάλε ελαιόλαδο σε ό,τι μαγειρεύεις.', sentenceEn: 'Put olive oil on everything you cook.' },
      { en: 'olives', gr: 'ελιές', sentence: 'Ελιές Καλαμάτας είναι οι καλύτερες.', sentenceEn: 'Kalamata olives are the best.' },
      { en: 'feta cheese', gr: 'φέτα', sentence: 'Φέτα χωρίς ελαιόλαδο; Αδύνατον.', sentenceEn: 'Feta without olive oil? Impossible.' },
      { en: 'bread', gr: 'ψωμί', sentence: 'Φρέσκο ψωμί από τον φούρνο.', sentenceEn: 'Fresh bread from the bakery.' },
      { en: 'butter', gr: 'βούτυρο', sentence: 'Βάζω βούτυρο στο ψωμί.', sentenceEn: 'I put butter on my bread.' },
      { en: 'honey', gr: 'μέλι', sentence: 'Γιαούρτι με μέλι — θεϊκό.', sentenceEn: 'Yoghurt with honey — divine.' },
      { en: 'yoghurt', gr: 'γιαούρτι', sentence: 'Το ελληνικό γιαούρτι είναι παχύ.', sentenceEn: 'Greek yoghurt is thick.' },
      { en: 'egg', gr: 'αυγό', sentence: 'Θέλω δύο αυγά βραστά.', sentenceEn: 'I want two boiled eggs.' },
      { en: 'tomato', gr: 'ντομάτα', sentence: 'Αυτή η ντομάτα μυρίζει καλοκαίρι.', sentenceEn: 'This tomato smells like summer.' },
      { en: 'cucumber', gr: 'αγγούρι', sentence: 'Κόψε αγγούρι για τη σαλάτα.', sentenceEn: 'Cut cucumber for the salad.' },
      { en: 'onion', gr: 'κρεμμύδι', sentence: 'Το κρεμμύδι με κάνει να κλαίω.', sentenceEn: 'The onion makes me cry.' },
      { en: 'garlic', gr: 'σκόρδο', sentence: 'Με σκόρδο όλα γίνονται καλύτερα.', sentenceEn: 'With garlic everything gets better.' },
      { en: 'lemon', gr: 'λεμόνι', sentence: 'Στύψε λεμόνι πάνω στο ψάρι.', sentenceEn: 'Squeeze lemon on the fish.' },
      { en: 'orange', gr: 'πορτοκάλι', sentence: 'Θέλεις ένα πορτοκάλι;', sentenceEn: 'Do you want an orange?' },
      { en: 'watermelon', gr: 'καρπούζι', sentence: 'Τίποτα δεν νικάει το καρπούζι τον Αύγουστο.', sentenceEn: 'Nothing beats watermelon in August.' },
      { en: 'grapes', gr: 'σταφύλια', sentence: 'Τα σταφύλια γίνονται κρασί.', sentenceEn: 'Grapes become wine.' },
      { en: 'apple', gr: 'μήλο', sentence: 'Ένα μήλο την ημέρα…', sentenceEn: 'An apple a day…' },
      { en: 'banana', gr: 'μπανάνα', sentence: 'Η μπανάνα είναι το τέλειο σνακ.', sentenceEn: 'The banana is the perfect snack.' },
      { en: 'Greek coffee', gr: 'ελληνικός καφές', sentence: 'Ένα ελληνικό μέτριο, παρακαλώ.', sentenceEn: 'One medium-sweet Greek coffee, please.' },
      { en: 'frappé', gr: 'φραπέ', sentence: 'Φραπέ στην παραλία — ελληνικό κλασικό.', sentenceEn: 'Frappé at the beach — a Greek classic.' },
      { en: 'tea', gr: 'τσάι', sentence: 'Πίνω τσάι όταν είμαι άρρωστος.', sentenceEn: 'I drink tea when I\'m sick.' },
      { en: 'orange juice', gr: 'χυμός πορτοκάλι', sentence: 'Ένα χυμό πορτοκάλι φρέσκο.', sentenceEn: 'A fresh-squeezed orange juice.' },
      { en: 'water', gr: 'νερό', sentence: 'Ένα μπουκάλι νερό, παρακαλώ.', sentenceEn: 'A bottle of water, please.' },
      { en: 'wine', gr: 'κρασί', sentence: 'Κόκκινο ή λευκό κρασί;', sentenceEn: 'Red or white wine?' },
      { en: 'beer', gr: 'μπύρα', sentence: 'Μια παγωμένη μπύρα μετά τη δουλειά.', sentenceEn: 'An ice-cold beer after work.' },
      { en: 'ice cream', gr: 'παγωτό', sentence: 'Δύο μπάλες παγωτό σοκολάτα.', sentenceEn: 'Two scoops of chocolate ice cream.' },
      { en: 'baklava', gr: 'μπακλαβάς', sentence: 'Ο μπακλαβάς είναι πολύ γλυκός αλλά υπέροχος.', sentenceEn: 'Baklava is very sweet but wonderful.' },
      { en: 'the bill', gr: 'ο λογαριασμός', sentence: 'Τον λογαριασμό, παρακαλώ!', sentenceEn: 'The bill, please!' },
    ],
  },
  {
    id: 'colours',
    title: 'Χρώματα',
    titleEn: 'Colours',
    icon: '🎨',
    words: [
      { en: 'red', gr: 'κόκκινο', sentence: 'Το κόκκινο αυτοκίνητο πήγαινε πολύ γρήγορα.', sentenceEn: 'The red car was going too fast.' },
      { en: 'blue', gr: 'μπλε', sentence: 'Η θάλασσα είναι βαθιά μπλε σήμερα.', sentenceEn: 'The sea is deep blue today.' },
      { en: 'green', gr: 'πράσινο', sentence: 'Το πάρκο είναι πολύ πράσινο την άνοιξη.', sentenceEn: 'The park is very green in spring.' },
      { en: 'yellow', gr: 'κίτρινο', sentence: 'Φόρεσε ένα κίτρινο φόρεμα.', sentenceEn: 'She wore a yellow dress.' },
      { en: 'white', gr: 'άσπρο', sentence: 'Τα σπίτια στη Σαντορίνη είναι άσπρα.', sentenceEn: 'The houses in Santorini are white.' },
      { en: 'black', gr: 'μαύρο', sentence: 'Η γάτα μου είναι ολόμαυρη.', sentenceEn: 'My cat is completely black.' },
      { en: 'orange', gr: 'πορτοκαλί', sentence: 'Ο ουρανός έγινε πορτοκαλί στο ηλιοβασίλεμα.', sentenceEn: 'The sky turned orange at sunset.' },
      { en: 'purple', gr: 'μοβ', sentence: 'Τα μοβ λουλούδια μυρίζουν ωραία.', sentenceEn: 'The purple flowers smell nice.' },
      { en: 'pink', gr: 'ροζ', sentence: 'Αγόρασε ροζ παπούτσια.', sentenceEn: 'She bought pink shoes.' },
      { en: 'brown', gr: 'καφέ', sentence: 'Ο σκύλος μου είναι καφέ.', sentenceEn: 'My dog is brown.' },
      { en: 'grey', gr: 'γκρι', sentence: 'Ο ουρανός ήταν γκρι όλη μέρα.', sentenceEn: 'The sky was grey all day.' },
      { en: 'gold', gr: 'χρυσό', sentence: 'Φορούσε ένα χρυσό δαχτυλίδι.', sentenceEn: 'She was wearing a gold ring.' },
      { en: 'silver', gr: 'ασημί', sentence: 'Το ασημί φεγγάρι λάμπει απόψε.', sentenceEn: 'The silver moon is shining tonight.' },
      { en: 'light blue', gr: 'γαλάζιο', sentence: 'Η σημαία της Ελλάδας είναι γαλάζια και λευκή.', sentenceEn: 'The Greek flag is light blue and white.' },
    ],
  },
  {
    id: 'emotions',
    title: 'Συναισθήματα',
    titleEn: 'Emotions',
    icon: '😊',
    words: [
      { en: 'happy', gr: 'χαρούμενος', sentence: 'Είμαι χαρούμενος γιατί είναι Παρασκευή!', sentenceEn: 'I\'m happy because it\'s Friday!' },
      { en: 'sad', gr: 'λυπημένος', sentence: 'Ο σκύλος φαίνεται λυπημένος σήμερα.', sentenceEn: 'The dog looks sad today.' },
      { en: 'tired', gr: 'κουρασμένος', sentence: 'Είμαι κουρασμένος μετά από δέκα ώρες δουλειά.', sentenceEn: 'I\'m tired after ten hours of work.' },
      { en: 'annoyed', gr: 'εκνευρισμένος', sentence: 'Είναι εκνευρισμένος γιατί χάνει πάντα στα παιχνίδια.', sentenceEn: 'He\'s annoyed because he always loses at games.' },
      { en: 'bored', gr: 'βαριεστημένος', sentence: 'Είμαι βαριεστημένος — πάμε κάπου;', sentenceEn: 'I\'m bored — shall we go somewhere?' },
      { en: 'angry', gr: 'θυμωμένος', sentence: 'Μην μιλάς του, είναι θυμωμένος.', sentenceEn: 'Don\'t talk to him, he\'s angry.' },
      { en: 'scared', gr: 'φοβισμένος', sentence: 'Η γάτα είναι φοβισμένη από τη βροχή.', sentenceEn: 'The cat is scared of the rain.' },
      { en: 'surprised', gr: 'έκπληκτος', sentence: 'Ήταν έκπληκτος όταν είδε το δώρο.', sentenceEn: 'He was surprised when he saw the gift.' },
      { en: 'excited', gr: 'ενθουσιασμένος', sentence: 'Τα παιδιά είναι ενθουσιασμένα για τις διακοπές.', sentenceEn: 'The kids are excited about the holiday.' },
      { en: 'worried', gr: 'ανήσυχος', sentence: 'Η μαμά μου είναι πάντα ανήσυχη.', sentenceEn: 'My mum is always worried.' },
      { en: 'calm', gr: 'ήρεμος', sentence: 'Μείνε ήρεμος, όλα θα πάνε καλά.', sentenceEn: 'Stay calm, everything will be fine.' },
      { en: 'proud', gr: 'περήφανος', sentence: 'Ο πατέρας μου είναι περήφανος για μένα.', sentenceEn: 'My father is proud of me.' },
      { en: 'embarrassed', gr: 'ντροπιασμένος', sentence: 'Ήταν ντροπιασμένος που έπεσε μπροστά σε όλους.', sentenceEn: 'He was embarrassed that he fell in front of everyone.' },
      { en: 'confused', gr: 'μπερδεμένος', sentence: 'Είμαι μπερδεμένος — ποιο είναι το σωστό;', sentenceEn: 'I\'m confused — which one is correct?' },
      { en: 'lonely', gr: 'μοναχικός', sentence: 'Νιώθω μοναχικός σ\' αυτή την πόλη.', sentenceEn: 'I feel lonely in this city.' },
      { en: 'grateful', gr: 'ευγνώμων', sentence: 'Είμαι ευγνώμων για τους φίλους μου.', sentenceEn: 'I\'m grateful for my friends.' },
      { en: 'jealous', gr: 'ζηλιάρης', sentence: 'Μην είσαι ζηλιάρης, έχεις πολλά!', sentenceEn: 'Don\'t be jealous, you have plenty!' },
      { en: 'nervous', gr: 'νευρικός', sentence: 'Είμαι νευρικός πριν τις εξετάσεις.', sentenceEn: 'I\'m nervous before exams.' },
      { en: 'relaxed', gr: 'χαλαρός', sentence: 'Είμαι πολύ χαλαρός στις διακοπές.', sentenceEn: 'I\'m very relaxed on holiday.' },
      { en: 'disappointed', gr: 'απογοητευμένος', sentence: 'Είναι απογοητευμένος με το αποτέλεσμα.', sentenceEn: 'He\'s disappointed with the result.' },
      { en: 'hopeful', gr: 'αισιόδοξος', sentence: 'Είμαι αισιόδοξος για το μέλλον.', sentenceEn: 'I\'m hopeful about the future.' },
      { en: 'frustrated', gr: 'απογοητευμένος', sentence: 'Είμαι τόσο απογοητευμένος με αυτόν τον υπολογιστή!', sentenceEn: 'I\'m so frustrated with this computer!' },
      { en: 'content', gr: 'ικανοποιημένος', sentence: 'Είμαι ικανοποιημένος με τη ζωή μου.', sentenceEn: 'I\'m content with my life.' },
      { en: 'anxious', gr: 'αγχωμένος', sentence: 'Είναι αγχωμένη για τη συνέντευξη.', sentenceEn: 'She\'s anxious about the interview.' },
      { en: 'nostalgic', gr: 'νοσταλγικός', sentence: 'Αυτό το τραγούδι με κάνει νοσταλγικό.', sentenceEn: 'This song makes me nostalgic.' },
      { en: 'enthusiastic', gr: 'ενθουσιώδης', sentence: 'Ο δάσκαλος είναι πολύ ενθουσιώδης.', sentenceEn: 'The teacher is very enthusiastic.' },
      { en: 'uncomfortable', gr: 'άβολος', sentence: 'Αυτή η καρέκλα είναι πολύ άβολη.', sentenceEn: 'This chair is very uncomfortable.' },
      { en: 'curious', gr: 'περίεργος', sentence: 'Τα παιδιά είναι πάντα περίεργα.', sentenceEn: 'Children are always curious.' },
      { en: 'shocked', gr: 'σοκαρισμένος', sentence: 'Ήμασταν σοκαρισμένοι με τα νέα.', sentenceEn: 'We were shocked by the news.' },
      { en: 'guilty', gr: 'ένοχος', sentence: 'Νιώθω ένοχος που έφαγα όλο το κέικ.', sentenceEn: 'I feel guilty that I ate the whole cake.' },
      { en: 'shy', gr: 'ντροπαλός', sentence: 'Ήταν πολύ ντροπαλός στο πάρτι.', sentenceEn: 'He was very shy at the party.' },
      { en: 'determined', gr: 'αποφασισμένος', sentence: 'Είναι αποφασισμένη να τελειώσει.', sentenceEn: 'She\'s determined to finish.' },
      { en: 'overwhelmed', gr: 'συγκλονισμένος', sentence: 'Είμαι συγκλονισμένος από τόση αγάπη.', sentenceEn: 'I\'m overwhelmed by so much love.' },
      { en: 'impatient', gr: 'ανυπόμονος', sentence: 'Ο μικρός είναι ανυπόμονος για τα Χριστούγεννα.', sentenceEn: 'The little one is impatient for Christmas.' },
      { en: 'inspired', gr: 'εμπνευσμένος', sentence: 'Νιώθω εμπνευσμένος μετά τη συναυλία.', sentenceEn: 'I feel inspired after the concert.' },
      { en: 'indifferent', gr: 'αδιάφορος', sentence: 'Είναι αδιάφορος για τα πάντα.', sentenceEn: 'He\'s indifferent about everything.' },
      { en: 'terrified', gr: 'τρομοκρατημένος', sentence: 'Είμαι τρομοκρατημένος από τις αράχνες.', sentenceEn: 'I\'m terrified of spiders.' },
      { en: 'relieved', gr: 'ανακουφισμένος', sentence: 'Είμαι ανακουφισμένος που πέρασα τις εξετάσεις.', sentenceEn: 'I\'m relieved that I passed the exams.' },
      { en: 'furious', gr: 'έξαλλος', sentence: 'Ο προπονητής ήταν έξαλλος μετά τον αγώνα.', sentenceEn: 'The coach was furious after the match.' },
      { en: 'moody', gr: 'κακόκεφος', sentence: 'Μην τον πειράζεις, είναι κακόκεφος.', sentenceEn: 'Don\'t tease him, he\'s moody.' },
    ],
  },
  {
    id: 'household',
    title: 'Σπίτι & Αντικείμενα',
    titleEn: 'Household nouns',
    icon: '🏠',
    words: [
      // Rooms & structure
      { en: 'house', gr: 'σπίτι', sentence: 'Το σπίτι μας έχει κήπο.', sentenceEn: 'Our house has a garden.' },
      { en: 'room', gr: 'δωμάτιο', sentence: 'Αυτό το δωμάτιο θέλει βάψιμο.', sentenceEn: 'This room needs painting.' },
      { en: 'kitchen', gr: 'κουζίνα', sentence: 'Η κουζίνα μυρίζει κανέλα.', sentenceEn: 'The kitchen smells of cinnamon.' },
      { en: 'bathroom', gr: 'μπάνιο', sentence: 'Το μπάνιο είναι κατειλημμένο — πάλι!', sentenceEn: 'The bathroom is occupied — again!' },
      { en: 'bedroom', gr: 'υπνοδωμάτιο', sentence: 'Το υπνοδωμάτιο πρέπει να είναι σκοτεινό.', sentenceEn: 'The bedroom should be dark.' },
      { en: 'living room', gr: 'σαλόνι', sentence: 'Καθόμαστε στο σαλόνι και βλέπουμε τηλεόραση.', sentenceEn: 'We sit in the living room and watch TV.' },
      { en: 'balcony', gr: 'μπαλκόνι', sentence: 'Πίνω καφέ στο μπαλκόνι κάθε πρωί.', sentenceEn: 'I drink coffee on the balcony every morning.' },
      { en: 'stairs', gr: 'σκάλες', sentence: 'Ανεβαίνω τις σκάλες τρέχοντας.', sentenceEn: 'I run up the stairs.' },
      { en: 'floor', gr: 'πάτωμα', sentence: 'Το πάτωμα είναι ξύλινο.', sentenceEn: 'The floor is wooden.' },
      { en: 'wall', gr: 'τοίχος', sentence: 'Κρέμασε έναν πίνακα στον τοίχο.', sentenceEn: 'She hung a painting on the wall.' },
      { en: 'ceiling', gr: 'ταβάνι', sentence: 'Η αράχνη περπατάει στο ταβάνι.', sentenceEn: 'The spider is walking on the ceiling.' },
      { en: 'door', gr: 'πόρτα', sentence: 'Κλείσε την πόρτα, μπαίνει κρύο.', sentenceEn: 'Close the door, it\'s getting cold.' },
      { en: 'window', gr: 'παράθυρο', sentence: 'Άνοιξε το παράθυρο να μπει αέρας.', sentenceEn: 'Open the window to let air in.' },
      // Living room
      { en: 'sofa', gr: 'καναπές', sentence: 'Ο καναπές είναι πολύ μαλακός.', sentenceEn: 'The sofa is very soft.' },
      { en: 'table', gr: 'τραπέζι', sentence: 'Βάλε τα πιάτα στο τραπέζι.', sentenceEn: 'Put the plates on the table.' },
      { en: 'chair', gr: 'καρέκλα', sentence: 'Τράβηξε μια καρέκλα και κάτσε.', sentenceEn: 'Pull up a chair and sit down.' },
      { en: 'television', gr: 'τηλεόραση', sentence: 'Η τηλεόραση είναι πάντα ανοιχτή.', sentenceEn: 'The television is always on.' },
      { en: 'lamp', gr: 'λάμπα', sentence: 'Η λάμπα στο σαλόνι χάλασε.', sentenceEn: 'The living room lamp broke.' },
      { en: 'carpet', gr: 'χαλί', sentence: 'Πάτησα στο χαλί με βρώμικα παπούτσια.', sentenceEn: 'I stepped on the carpet with dirty shoes.' },
      { en: 'bookshelf', gr: 'βιβλιοθήκη', sentence: 'Η βιβλιοθήκη είναι γεμάτη.', sentenceEn: 'The bookshelf is full.' },
      { en: 'curtains', gr: 'κουρτίνες', sentence: 'Τράβηξε τις κουρτίνες, μπαίνει ήλιος.', sentenceEn: 'Draw the curtains, the sun is coming in.' },
      // Kitchen
      { en: 'fridge', gr: 'ψυγείο', sentence: 'Το ψυγείο είναι σχεδόν άδειο.', sentenceEn: 'The fridge is almost empty.' },
      { en: 'oven', gr: 'φούρνος', sentence: 'Ο φούρνος προθερμαίνεται.', sentenceEn: 'The oven is preheating.' },
      { en: 'microwave', gr: 'φούρνος μικροκυμάτων', sentence: 'Ζέστανε το φαγητό στον φούρνο μικροκυμάτων.', sentenceEn: 'Heat the food in the microwave.' },
      { en: 'sink', gr: 'νεροχύτης', sentence: 'Ο νεροχύτης είναι γεμάτος πιάτα.', sentenceEn: 'The sink is full of dishes.' },
      { en: 'plate', gr: 'πιάτο', sentence: 'Πρόσεχε, το πιάτο είναι ζεστό!', sentenceEn: 'Be careful, the plate is hot!' },
      { en: 'glass', gr: 'ποτήρι', sentence: 'Το ποτήρι έπεσε και έσπασε.', sentenceEn: 'The glass fell and broke.' },
      { en: 'fork', gr: 'πιρούνι', sentence: 'Δώσε μου ένα πιρούνι, παρακαλώ.', sentenceEn: 'Give me a fork, please.' },
      { en: 'knife', gr: 'μαχαίρι', sentence: 'Αυτό το μαχαίρι κόβει πολύ.', sentenceEn: 'This knife is very sharp.' },
      { en: 'spoon', gr: 'κουτάλι', sentence: 'Χρειάζομαι κουτάλι για τη σούπα.', sentenceEn: 'I need a spoon for the soup.' },
      { en: 'pot', gr: 'κατσαρόλα', sentence: 'Η κατσαρόλα βράζει.', sentenceEn: 'The pot is boiling.' },
      { en: 'frying pan', gr: 'τηγάνι', sentence: 'Βάλε λάδι στο τηγάνι.', sentenceEn: 'Put oil in the frying pan.' },
      // Bedroom
      { en: 'bed', gr: 'κρεβάτι', sentence: 'Δεν θέλω να σηκωθώ από το κρεβάτι.', sentenceEn: 'I don\'t want to get out of bed.' },
      { en: 'pillow', gr: 'μαξιλάρι', sentence: 'Χρειάζομαι δύο μαξιλάρια.', sentenceEn: 'I need two pillows.' },
      { en: 'blanket', gr: 'κουβέρτα', sentence: 'Αυτή η κουβέρτα είναι πολύ ζεστή.', sentenceEn: 'This blanket is very warm.' },
      { en: 'wardrobe', gr: 'ντουλάπα', sentence: 'Η ντουλάπα δεν κλείνει πια.', sentenceEn: 'The wardrobe won\'t close anymore.' },
      { en: 'alarm clock', gr: 'ξυπνητήρι', sentence: 'Μισώ τον ήχο του ξυπνητηριού.', sentenceEn: 'I hate the sound of the alarm clock.' },
      { en: 'mirror', gr: 'καθρέφτης', sentence: 'Κοιτάχτηκε στον καθρέφτη.', sentenceEn: 'She looked at herself in the mirror.' },
      // Bathroom
      { en: 'towel', gr: 'πετσέτα', sentence: 'Δώσε μου μια καθαρή πετσέτα.', sentenceEn: 'Give me a clean towel.' },
      { en: 'soap', gr: 'σαπούνι', sentence: 'Το σαπούνι μυρίζει λεβάντα.', sentenceEn: 'The soap smells like lavender.' },
      { en: 'shower', gr: 'ντους', sentence: 'Κάνω ντους κάθε πρωί.', sentenceEn: 'I take a shower every morning.' },
      { en: 'bathtub', gr: 'μπανιέρα', sentence: 'Η μπανιέρα είναι γεμάτη αφρό.', sentenceEn: 'The bathtub is full of bubbles.' },
      { en: 'toilet', gr: 'τουαλέτα', sentence: 'Η τουαλέτα είναι στα αριστερά.', sentenceEn: 'The toilet is on the left.' },
      { en: 'toothbrush', gr: 'οδοντόβουρτσα', sentence: 'Ξέχασα την οδοντόβουρτσά μου.', sentenceEn: 'I forgot my toothbrush.' },
      // Office
      { en: 'desk', gr: 'γραφείο', sentence: 'Το γραφείο μου είναι χάος.', sentenceEn: 'My desk is chaos.' },
      { en: 'computer', gr: 'υπολογιστής', sentence: 'Ο υπολογιστής δουλεύει αργά.', sentenceEn: 'The computer is running slowly.' },
      { en: 'key', gr: 'κλειδί', sentence: 'Πού είναι τα κλειδιά;', sentenceEn: 'Where are the keys?' },
      { en: 'rubbish bin', gr: 'κάδος σκουπιδιών', sentence: 'Πέτα το στον κάδο σκουπιδιών.', sentenceEn: 'Throw it in the rubbish bin.' },
      { en: 'washing machine', gr: 'πλυντήριο', sentence: 'Το πλυντήριο τελείωσε.', sentenceEn: 'The washing machine finished.' },
      { en: 'iron', gr: 'σίδερο', sentence: 'Πρέπει να σιδερώσω με το σίδερο.', sentenceEn: 'I have to iron with the iron.' },
    ],
  },
  {
    id: 'body-parts',
    title: 'Μέρη του σώματος',
    titleEn: 'Body parts',
    icon: '🦴',
    words: [
      { en: 'head', gr: 'κεφάλι', sentence: 'Με πονάει το κεφάλι μου.', sentenceEn: 'My head hurts.' },
      { en: 'face', gr: 'πρόσωπο', sentence: 'Το πρόσωπό του κοκκίνισε.', sentenceEn: 'His face turned red.' },
      { en: 'eye', gr: 'μάτι', sentence: 'Έχει πράσινα μάτια.', sentenceEn: 'She has green eyes.' },
      { en: 'ear', gr: 'αυτί', sentence: 'Ο σκύλος κουνάει τα αυτιά του.', sentenceEn: 'The dog is wagging his ears.' },
      { en: 'nose', gr: 'μύτη', sentence: 'Η μύτη μου είναι κρύα.', sentenceEn: 'My nose is cold.' },
      { en: 'mouth', gr: 'στόμα', sentence: 'Κλείσε το στόμα σου και φάε.', sentenceEn: 'Close your mouth and eat.' },
      { en: 'tooth', gr: 'δόντι', sentence: 'Με πονάει ένα δόντι.', sentenceEn: 'A tooth is hurting me.' },
      { en: 'neck', gr: 'λαιμός', sentence: 'Ο λαιμός μου πιάστηκε.', sentenceEn: 'My neck is stiff.' },
      { en: 'shoulder', gr: 'ώμος', sentence: 'Χτύπησα τον ώμο μου στην πόρτα.', sentenceEn: 'I hit my shoulder on the door.' },
      { en: 'arm', gr: 'μπράτσο', sentence: 'Σήκωσε τα μπράτσα σου ψηλά!', sentenceEn: 'Raise your arms high!' },
      { en: 'hand', gr: 'χέρι', sentence: 'Πλύνε τα χέρια σου πριν φας.', sentenceEn: 'Wash your hands before you eat.' },
      { en: 'finger', gr: 'δάχτυλο', sentence: 'Κόπηκα στο δάχτυλο.', sentenceEn: 'I cut my finger.' },
      { en: 'chest', gr: 'στήθος', sentence: 'Πονάει στο στήθος.', sentenceEn: 'His chest hurts.' },
      { en: 'back', gr: 'πλάτη', sentence: 'Η πλάτη μου με σκοτώνει.', sentenceEn: 'My back is killing me.' },
      { en: 'stomach', gr: 'στομάχι', sentence: 'Το στομάχι μου κάνει θόρυβο.', sentenceEn: 'My stomach is making noise.' },
      { en: 'leg', gr: 'πόδι', sentence: 'Τα πόδια μου κουράστηκαν από το περπάτημα.', sentenceEn: 'My legs are tired from walking.' },
      { en: 'knee', gr: 'γόνατο', sentence: 'Χτύπησα το γόνατό μου στο τραπέζι.', sentenceEn: 'I hit my knee on the table.' },
      { en: 'foot', gr: 'πατούσα', sentence: 'Πάτησα κάτι με τη γυμνή πατούσα.', sentenceEn: 'I stepped on something with my bare foot.' },
      { en: 'hair', gr: 'μαλλιά', sentence: 'Τα μαλλιά της είναι πολύ μακριά.', sentenceEn: 'Her hair is very long.' },
      { en: 'heart', gr: 'καρδιά', sentence: 'Η καρδιά μου χτυπάει γρήγορα.', sentenceEn: 'My heart is beating fast.' },
    ],
  },
];
