// ═══════════════════════════════════════════════════════════════════════════════
// THEMATIC LESSON DATA
// ═══════════════════════════════════════════════════════════════════════════════
const THEMATIC_LESSONS = [
  {
    id: 'days-of-week',
    title: 'Μέρες της εβδομάδας',
    titleEn: 'Days of the week',
    icon: '📅',
    words: [
      { en: 'Monday', gr: 'Δευτέρα', sentence: 'Κάθε Δευτέρα πρωί λέω ότι θα πάω γυμναστήριο, αλλά τελικά πάντα καταλήγω στον καναπέ.', sentenceEn: 'Every Monday morning I say I\'ll go to the gym, but I always end up on the sofa.' },
      { en: 'Tuesday', gr: 'Τρίτη', sentence: 'Την Τρίτη έχουμε συνάντηση στη δουλειά που δεν τελειώνει ποτέ — σοβαρά, κρατάει τρεις ώρες.', sentenceEn: 'On Tuesday we have a work meeting that never ends — seriously, it lasts three hours.' },
      { en: 'Wednesday', gr: 'Τετάρτη', sentence: 'Η Τετάρτη είναι η μέρα που λέμε «ευτυχώς, πέρασε η μισή εβδομάδα», σωστά;', sentenceEn: 'Wednesday is the day we say "thankfully, half the week is over", right?' },
      { en: 'Thursday', gr: 'Πέμπτη', sentence: 'Την Πέμπτη το βράδυ ετοιμάζω τη βαλίτσα μου γιατί φεύγω για Θεσσαλονίκη το πρωί.', sentenceEn: 'On Thursday evening I pack my suitcase because I\'m leaving for Thessaloniki in the morning.' },
      { en: 'Friday', gr: 'Παρασκευή', sentence: 'Ποιος δουλεύει Παρασκευή απόγευμα; Εγώ όχι — κλείνω τον υπολογιστή στις τρεις!', sentenceEn: 'Who works on Friday afternoon? Not me — I close my laptop at three!' },
      { en: 'Saturday', gr: 'Σάββατο', sentence: 'Το Σάββατο ξυπνήσαμε στις δώδεκα και πήγαμε για μπρούντς στην παραλία.', sentenceEn: 'On Saturday we woke up at noon and went for brunch by the beach.' },
      { en: 'Sunday', gr: 'Κυριακή', sentence: 'Την Κυριακή η γιαγιά μαγειρεύει για δεκαπέντε άτομα, ακόμα κι αν είμαστε μόνο πέντε.', sentenceEn: 'On Sunday grandma cooks for fifteen people, even if there are only five of us.' },
    ],
  },
  {
    id: 'telling-time',
    title: 'Η ώρα',
    titleEn: 'Telling the time',
    icon: '🕐',
    words: [
      { en: 'What time is it?', gr: 'Τι ώρα είναι;', sentence: 'Συγγνώμη, τι ώρα είναι; Νομίζω αργώ.', sentenceEn: 'Excuse me, what time is it? I think I\'m late.' },
      { en: 'one o\'clock', gr: 'μία η ώρα', sentence: 'Είναι μία η ώρα και πεινάω.', sentenceEn: 'It\'s one o\'clock and I\'m hungry.' },
      { en: 'two o\'clock', gr: 'δύο η ώρα', sentence: 'Ελάτε στις δύο, θα είμαστε έτοιμοι.', sentenceEn: 'Come at two, we\'ll be ready.' },
      { en: 'three o\'clock', gr: 'τρεις η ώρα', sentence: 'Ποιος χτυπάει την πόρτα στις τρεις τη νύχτα;', sentenceEn: 'Who knocks on the door at three in the morning?' },
      { en: 'four o\'clock', gr: 'τέσσερις η ώρα', sentence: 'Ο καφές είναι στις τέσσερις.', sentenceEn: 'Coffee is at four o\'clock.' },
      { en: 'five o\'clock', gr: 'πέντε η ώρα', sentence: 'Στις πέντε σταματάω ό,τι κάνω και φεύγω.', sentenceEn: 'At five I stop whatever I\'m doing and leave.' },
      { en: 'six o\'clock', gr: 'έξι η ώρα', sentence: 'Το ηλιοβασίλεμα στις έξι ήταν απίστευτο.', sentenceEn: 'The sunset at six was incredible.' },
      { en: 'seven o\'clock', gr: 'εφτά η ώρα', sentence: 'Ξυπνάω στις εφτά κάθε μέρα.', sentenceEn: 'I wake up at seven every day.' },
      { en: 'eight o\'clock', gr: 'οχτώ η ώρα', sentence: 'Βιάσου, η ταινία αρχίζει στις οχτώ!', sentenceEn: 'Hurry, the movie starts at eight!' },
      { en: 'nine o\'clock', gr: 'εννιά η ώρα', sentence: 'Στις εννιά τα παιδιά πρέπει να κοιμηθούν.', sentenceEn: 'At nine the kids need to go to sleep.' },
      { en: 'ten o\'clock', gr: 'δέκα η ώρα', sentence: 'Στις δέκα κλείνει το μαγαζί.', sentenceEn: 'The shop closes at ten.' },
      { en: 'eleven o\'clock', gr: 'έντεκα η ώρα', sentence: 'Ποιος τρώει μεσημεριανό στις έντεκα;', sentenceEn: 'Who eats lunch at eleven?' },
      { en: 'twelve o\'clock', gr: 'δώδεκα η ώρα', sentence: 'Στις δώδεκα ακριβώς χτυπάει η καμπάνα.', sentenceEn: 'At exactly twelve the bell rings.' },
      { en: 'quarter past', gr: 'και τέταρτο', sentence: 'Είναι τρεις και τέταρτο, πού είσαι;', sentenceEn: 'It\'s quarter past three, where are you?' },
      { en: 'half past', gr: 'και μισή', sentence: 'Θα φτάσω στις εφτά και μισή περίπου.', sentenceEn: 'I\'ll arrive at about half past seven.' },
      { en: 'quarter to', gr: 'παρά τέταρτο', sentence: 'Φεύγουμε στις δέκα παρά τέταρτο, ετοιμάσου.', sentenceEn: 'We leave at quarter to ten, get ready.' },
      { en: 'in the morning', gr: 'το πρωί', sentence: 'Το πρωί χωρίς καφέ δεν λειτουργώ.', sentenceEn: 'In the morning without coffee I can\'t function.' },
      { en: 'in the afternoon', gr: 'το απόγευμα', sentence: 'Το απόγευμα θα πάμε μια βόλτα;', sentenceEn: 'Shall we go for a walk in the afternoon?' },
      { en: 'in the evening', gr: 'το βράδυ', sentence: 'Το βράδυ βλέπουμε ταινία.', sentenceEn: 'In the evening we watch a movie.' },
      { en: 'at midnight', gr: 'τα μεσάνυχτα', sentence: 'Τα μεσάνυχτα ο γείτονας βάζει δυνατά μουσική.', sentenceEn: 'At midnight the neighbour puts on loud music.' },
    ],
  },
  {
    id: 'restaurant-menu',
    title: 'Εστιατόριο & Καφέ',
    titleEn: 'Restaurant & cafe menu',
    icon: '🍽️',
    words: [
      { en: 'Greek salad', gr: 'χωριάτικη σαλάτα', sentence: 'Μία χωριάτικη χωρίς κρεμμύδι, παρακαλώ.', sentenceEn: 'One Greek salad without onion, please.' },
      { en: 'tzatziki', gr: 'τζατζίκι', sentence: 'Βάλε περισσότερο σκόρδο στο τζατζίκι.', sentenceEn: 'Put more garlic in the tzatziki.' },
      { en: 'pita bread', gr: 'πίτα', sentence: 'Θέλω πίτα ζεστή, όχι κρύα!', sentenceEn: 'I want hot pita, not cold!' },
      { en: 'grilled meat', gr: 'ψητό κρέας', sentence: 'Μυρίζει ψητό κρέας, ποιος μαγειρεύει;', sentenceEn: 'It smells of grilled meat, who\'s cooking?' },
      { en: 'souvlaki', gr: 'σουβλάκι', sentence: 'Ένα σουβλάκι κοτόπουλο με τα πάντα.', sentenceEn: 'One chicken souvlaki with everything.' },
      { en: 'gyros', gr: 'γύρος', sentence: 'Γύρος στις δύο τη νύχτα — κλασικό.', sentenceEn: 'Gyros at two in the morning — classic.' },
      { en: 'moussaka', gr: 'μουσακάς', sentence: 'Δοκίμασες τον μουσακά εδώ; Είναι τέλειος.', sentenceEn: 'Have you tried the moussaka here? It\'s perfect.' },
      { en: 'stuffed vine leaves', gr: 'ντολμαδάκια', sentence: 'Τα ντολμαδάκια θέλουν λεμόνι.', sentenceEn: 'Stuffed vine leaves need lemon.' },
      { en: 'spinach pie', gr: 'σπανακόπιτα', sentence: 'Πήρα σπανακόπιτα από τον φούρνο της γωνίας.', sentenceEn: 'I got spinach pie from the corner bakery.' },
      { en: 'cheese pie', gr: 'τυρόπιτα', sentence: 'Τυρόπιτα για πρωινό, τι καλύτερο;', sentenceEn: 'Cheese pie for breakfast, what\'s better?' },
      { en: 'fried cheese', gr: 'σαγανάκι', sentence: 'Σαγανάκι και μπύρα — τι άλλο θέλεις;', sentenceEn: 'Fried cheese and beer — what else do you need?' },
      { en: 'grilled octopus', gr: 'χταπόδι σχάρας', sentence: 'Πάρε το χταπόδι, είναι φανταστικό εδώ.', sentenceEn: 'Get the octopus, it\'s amazing here.' },
      { en: 'calamari', gr: 'καλαμαράκια', sentence: 'Τα καλαμαράκια ήταν τραγανά και ζεστά.', sentenceEn: 'The calamari were crispy and hot.' },
      { en: 'shrimp', gr: 'γαρίδες', sentence: 'Θέλω γαρίδες σαγανάκι.', sentenceEn: 'I want shrimp saganaki.' },
      { en: 'fish', gr: 'ψάρι', sentence: 'Το ψάρι είναι φρέσκο σήμερα.', sentenceEn: 'The fish is fresh today.' },
      { en: 'lamb chops', gr: 'παϊδάκια', sentence: 'Τα παϊδάκια στα κάρβουνα είναι τα καλύτερα.', sentenceEn: 'The lamb chops on charcoal are the best.' },
      { en: 'meatballs', gr: 'κεφτέδες', sentence: 'Η γιαγιά φτιάχνει κεφτέδες κάθε Κυριακή.', sentenceEn: 'Grandma makes meatballs every Sunday.' },
      { en: 'stuffed peppers', gr: 'γεμιστά', sentence: 'Τα γεμιστά σήμερα έχουν ρύζι και μυρωδικά.', sentenceEn: 'The stuffed peppers today have rice and herbs.' },
      { en: 'chips / French fries', gr: 'πατάτες τηγανητές', sentence: 'Πατάτες τηγανητές δίπλα στη θάλασσα!', sentenceEn: 'French fries by the sea!' },
      { en: 'rice', gr: 'ρύζι', sentence: 'Θέλεις ρύζι ή πατάτες;', sentenceEn: 'Do you want rice or potatoes?' },
      { en: 'lentil soup', gr: 'φακές', sentence: 'Η Μαρία φτιάχνει φακές κάθε Τετάρτη.', sentenceEn: 'Maria makes lentil soup every Wednesday.' },
      { en: 'bean soup', gr: 'φασολάδα', sentence: 'Φασολάδα τον χειμώνα σε ζεσταίνει αμέσως.', sentenceEn: 'Bean soup in winter warms you right up.' },
      { en: 'olive oil', gr: 'ελαιόλαδο', sentence: 'Ο Νίκος βάζει ελαιόλαδο σε τα πάντα.', sentenceEn: 'Nikos puts olive oil on everything.' },
      { en: 'olives', gr: 'ελιές', sentence: 'Ελιές Καλαμάτας είναι οι καλύτερες.', sentenceEn: 'Kalamata olives are the best.' },
      { en: 'feta cheese', gr: 'φέτα', sentence: 'Φέτα χωρίς ελαιόλαδο; Αδύνατον.', sentenceEn: 'Feta without olive oil? Impossible.' },
      { en: 'bread', gr: 'ψωμί', sentence: 'Ο Γιώργος πήγε να πάρει ψωμί φρέσκο.', sentenceEn: 'Giorgos went to get fresh bread.' },
      { en: 'butter', gr: 'βούτυρο', sentence: 'Βάζω βούτυρο στο ψωμί.', sentenceEn: 'I put butter on my bread.' },
      { en: 'honey', gr: 'μέλι', sentence: 'Γιαούρτι με μέλι — θεϊκό.', sentenceEn: 'Yoghurt with honey — divine.' },
      { en: 'yoghurt', gr: 'γιαούρτι', sentence: 'Η Ελένη τρώει γιαούρτι κάθε πρωί.', sentenceEn: 'Eleni eats yoghurt every morning.' },
      { en: 'egg', gr: 'αυγό', sentence: 'Πόσα αυγά θέλεις, δύο ή τρία;', sentenceEn: 'How many eggs do you want, two or three?' },
      { en: 'tomato', gr: 'ντομάτα', sentence: 'Αυτή η ντομάτα μυρίζει καλοκαίρι.', sentenceEn: 'This tomato smells like summer.' },
      { en: 'cucumber', gr: 'αγγούρι', sentence: 'Κόψε αγγούρι για τη σαλάτα.', sentenceEn: 'Cut cucumber for the salad.' },
      { en: 'onion', gr: 'κρεμμύδι', sentence: 'Ο Κώστας κόβει κρεμμύδι και κλαίει.', sentenceEn: 'Kostas is cutting onion and crying.' },
      { en: 'garlic', gr: 'σκόρδο', sentence: 'Με σκόρδο όλα γίνονται καλύτερα.', sentenceEn: 'With garlic everything gets better.' },
      { en: 'lemon', gr: 'λεμόνι', sentence: 'Στύψε λεμόνι πάνω στο ψάρι.', sentenceEn: 'Squeeze lemon on the fish.' },
      { en: 'orange', gr: 'πορτοκάλι', sentence: 'Η Σοφία μου έδωσε ένα πορτοκάλι.', sentenceEn: 'Sofia gave me an orange.' },
      { en: 'watermelon', gr: 'καρπούζι', sentence: 'Καρπούζι τον Αύγουστο δεν νικιέται.', sentenceEn: 'Watermelon in August can\'t be beat.' },
      { en: 'grapes', gr: 'σταφύλια', sentence: 'Τα σταφύλια γίνονται κρασί.', sentenceEn: 'Grapes become wine.' },
      { en: 'apple', gr: 'μήλο', sentence: 'Πάρε ένα μήλο για τον δρόμο.', sentenceEn: 'Grab an apple for the road.' },
      { en: 'banana', gr: 'μπανάνα', sentence: 'Ο Δημήτρης τρώει μπανάνα μετά το γυμναστήριο.', sentenceEn: 'Dimitris eats a banana after the gym.' },
      { en: 'Greek coffee', gr: 'ελληνικός καφές', sentence: 'Ένα ελληνικό μέτριο, παρακαλώ.', sentenceEn: 'One medium-sweet Greek coffee, please.' },
      { en: 'frappé', gr: 'φραπέ', sentence: 'Φραπέ στην παραλία — κλασικό καλοκαίρι.', sentenceEn: 'Frappé at the beach — classic summer.' },
      { en: 'tea', gr: 'τσάι', sentence: 'Η Αθηνά πίνει τσάι κάθε βράδυ.', sentenceEn: 'Athina drinks tea every evening.' },
      { en: 'orange juice', gr: 'χυμός πορτοκάλι', sentence: 'Ένα χυμό πορτοκάλι φρέσκο, παρακαλώ.', sentenceEn: 'A fresh orange juice, please.' },
      { en: 'water', gr: 'νερό', sentence: 'Ένα μπουκάλι νερό, παρακαλώ.', sentenceEn: 'A bottle of water, please.' },
      { en: 'wine', gr: 'κρασί', sentence: 'Κόκκινο ή λευκό κρασί;', sentenceEn: 'Red or white wine?' },
      { en: 'beer', gr: 'μπύρα', sentence: 'Μια παγωμένη μπύρα μετά τη δουλειά.', sentenceEn: 'An ice-cold beer after work.' },
      { en: 'ice cream', gr: 'παγωτό', sentence: 'Ο Γιάννης πήρε τρεις μπάλες παγωτό.', sentenceEn: 'Yiannis got three scoops of ice cream.' },
      { en: 'baklava', gr: 'μπακλαβάς', sentence: 'Ο μπακλαβάς είναι γλυκός αλλά υπέροχος.', sentenceEn: 'Baklava is sweet but wonderful.' },
      { en: 'the bill', gr: 'ο λογαριασμός', sentence: 'Τον λογαριασμό, παρακαλώ!', sentenceEn: 'The bill, please!' },
    ],
  },
  {
    id: 'colours',
    title: 'Χρώματα',
    titleEn: 'Colours',
    icon: '🎨',
    words: [
      { en: 'red', gr: 'κόκκινο', sentence: 'Ο Γιάννης αγόρασε ένα κόκκινο αυτοκίνητο.', sentenceEn: 'Yiannis bought a red car.' },
      { en: 'blue', gr: 'μπλε', sentence: 'Η θάλασσα είναι βαθιά μπλε σήμερα.', sentenceEn: 'The sea is deep blue today.' },
      { en: 'green', gr: 'πράσινο', sentence: 'Το πάρκο γίνεται πράσινο την άνοιξη.', sentenceEn: 'The park turns green in spring.' },
      { en: 'yellow', gr: 'κίτρινο', sentence: 'Η Σοφία φόρεσε ένα κίτρινο φόρεμα.', sentenceEn: 'Sofia wore a yellow dress.' },
      { en: 'white', gr: 'άσπρο', sentence: 'Τα σπίτια στη Σαντορίνη είναι άσπρα.', sentenceEn: 'The houses in Santorini are white.' },
      { en: 'black', gr: 'μαύρο', sentence: 'Η γάτα μου είναι ολόμαυρη.', sentenceEn: 'My cat is completely black.' },
      { en: 'orange', gr: 'πορτοκαλί', sentence: 'Ο ουρανός έγινε πορτοκαλί στο ηλιοβασίλεμα.', sentenceEn: 'The sky turned orange at sunset.' },
      { en: 'purple', gr: 'μοβ', sentence: 'Τα μοβ λουλούδια μυρίζουν ωραία.', sentenceEn: 'The purple flowers smell nice.' },
      { en: 'pink', gr: 'ροζ', sentence: 'Η Ελένη αγόρασε ροζ παπούτσια.', sentenceEn: 'Eleni bought pink shoes.' },
      { en: 'brown', gr: 'καφέ', sentence: 'Ο σκύλος του Κώστα είναι καφέ.', sentenceEn: 'Kostas\'s dog is brown.' },
      { en: 'grey', gr: 'γκρι', sentence: 'Ο ουρανός ήταν γκρι όλη μέρα.', sentenceEn: 'The sky was grey all day.' },
      { en: 'gold', gr: 'χρυσό', sentence: 'Η Μαρία φορούσε ένα χρυσό δαχτυλίδι.', sentenceEn: 'Maria was wearing a gold ring.' },
      { en: 'silver', gr: 'ασημί', sentence: 'Το ασημί φεγγάρι λάμπει απόψε.', sentenceEn: 'The silver moon is shining tonight.' },
      { en: 'light blue', gr: 'γαλάζιο', sentence: 'Η ελληνική σημαία είναι γαλάζια και λευκή.', sentenceEn: 'The Greek flag is light blue and white.' },
    ],
  },
  {
    id: 'emotions',
    title: 'Συναισθήματα',
    titleEn: 'Emotions',
    icon: '😊',
    words: [
      { en: 'happy', gr: 'χαρούμενος', sentence: 'Ο Νίκος είναι χαρούμενος, πήρε προαγωγή.', sentenceEn: 'Nikos is happy, he got a promotion.' },
      { en: 'sad', gr: 'λυπημένος', sentence: 'Ο σκύλος φαίνεται λυπημένος σήμερα.', sentenceEn: 'The dog looks sad today.' },
      { en: 'tired', gr: 'κουρασμένος', sentence: 'Ο Δημήτρης είναι κουρασμένος μετά τη δουλειά.', sentenceEn: 'Dimitris is tired after work.' },
      { en: 'annoyed', gr: 'εκνευρισμένος', sentence: 'Ο Κώστας είναι εκνευρισμένος με τον γείτονα.', sentenceEn: 'Kostas is annoyed with the neighbour.' },
      { en: 'bored', gr: 'βαριεστημένος', sentence: 'Είμαι βαριεστημένος — πάμε κάπου;', sentenceEn: 'I\'m bored — shall we go somewhere?' },
      { en: 'angry', gr: 'θυμωμένος', sentence: 'Μην του μιλάς, είναι θυμωμένος.', sentenceEn: 'Don\'t talk to him, he\'s angry.' },
      { en: 'scared', gr: 'φοβισμένος', sentence: 'Η γάτα είναι φοβισμένη από τη βροχή.', sentenceEn: 'The cat is scared of the rain.' },
      { en: 'surprised', gr: 'έκπληκτος', sentence: 'Ο Γιώργος ήταν έκπληκτος — δεν το περίμενε.', sentenceEn: 'Giorgos was surprised — he didn\'t expect it.' },
      { en: 'excited', gr: 'ενθουσιασμένος', sentence: 'Η Σοφία είναι ενθουσιασμένη, φεύγει αύριο!', sentenceEn: 'Sofia is excited, she leaves tomorrow!' },
      { en: 'worried', gr: 'ανήσυχος', sentence: 'Γιατί είσαι ανήσυχος, τι έγινε;', sentenceEn: 'Why are you worried, what happened?' },
      { en: 'calm', gr: 'ήρεμος', sentence: 'Μείνε ήρεμος, δεν είναι τίποτα.', sentenceEn: 'Stay calm, it\'s nothing.' },
      { en: 'proud', gr: 'περήφανος', sentence: 'Η Αθηνά είναι περήφανη για τον γιο της.', sentenceEn: 'Athina is proud of her son.' },
      { en: 'embarrassed', gr: 'ντροπιασμένος', sentence: 'Ο Γιάννης ντράπηκε που μίλησε λάθος.', sentenceEn: 'Yiannis was embarrassed he misspoke.' },
      { en: 'confused', gr: 'μπερδεμένος', sentence: 'Είμαι μπερδεμένος — ποιο είναι το σωστό;', sentenceEn: 'I\'m confused — which one is correct?' },
      { en: 'lonely', gr: 'μοναχικός', sentence: 'Η Ελένη νιώθει μοναχική στη νέα πόλη.', sentenceEn: 'Eleni feels lonely in the new city.' },
      { en: 'grateful', gr: 'ευγνώμων', sentence: 'Είμαι ευγνώμων για τους φίλους μου.', sentenceEn: 'I\'m grateful for my friends.' },
      { en: 'jealous', gr: 'ζηλιάρης', sentence: 'Μην είσαι ζηλιάρης, έχεις πολλά!', sentenceEn: 'Don\'t be jealous, you have plenty!' },
      { en: 'nervous', gr: 'νευρικός', sentence: 'Ο Κώστας είναι νευρικός πριν το ματς.', sentenceEn: 'Kostas is nervous before the match.' },
      { en: 'relaxed', gr: 'χαλαρός', sentence: 'Μετά τη θάλασσα είμαι τελείως χαλαρός.', sentenceEn: 'After the sea I\'m totally relaxed.' },
      { en: 'disappointed', gr: 'απογοητευμένος', sentence: 'Ο Νίκος είναι απογοητευμένος, δεν πέρασε.', sentenceEn: 'Nikos is disappointed, he didn\'t pass.' },
      { en: 'hopeful', gr: 'αισιόδοξος', sentence: 'Παρ\' όλα αυτά, είμαι αισιόδοξος.', sentenceEn: 'Despite everything, I\'m hopeful.' },
      { en: 'frustrated', gr: 'ματαιωμένος', sentence: 'Είναι ματαιωμένος, τίποτα δεν δουλεύει σήμερα.', sentenceEn: 'He\'s frustrated, nothing works today.' },
      { en: 'content', gr: 'ικανοποιημένος', sentence: 'Η Μαρία είναι ικανοποιημένη με τη δουλειά.', sentenceEn: 'Maria is content with her job.' },
      { en: 'anxious', gr: 'αγχωμένος', sentence: 'Η Σοφία είναι αγχωμένη για τη συνέντευξη.', sentenceEn: 'Sofia is anxious about the interview.' },
      { en: 'nostalgic', gr: 'νοσταλγικός', sentence: 'Αυτό το τραγούδι με κάνει νοσταλγικό.', sentenceEn: 'This song makes me nostalgic.' },
      { en: 'enthusiastic', gr: 'ενθουσιώδης', sentence: 'Ο Δημήτρης είναι ενθουσιώδης με τα πάντα.', sentenceEn: 'Dimitris is enthusiastic about everything.' },
      { en: 'uncomfortable', gr: 'άβολος', sentence: 'Ήταν λίγο άβολο, δεν ήξερα κανέναν.', sentenceEn: 'It was a bit uncomfortable, I knew nobody.' },
      { en: 'curious', gr: 'περίεργος', sentence: 'Ο Γιώργος είναι περίεργος, ρωτάει συνέχεια.', sentenceEn: 'Giorgos is curious, he asks nonstop.' },
      { en: 'shocked', gr: 'σοκαρισμένος', sentence: 'Η Αθηνά έμεινε σοκαρισμένη με την τιμή.', sentenceEn: 'Athina was shocked by the price.' },
      { en: 'guilty', gr: 'ένοχος', sentence: 'Νιώθω ένοχος που έφαγα όλο το κέικ.', sentenceEn: 'I feel guilty that I ate the whole cake.' },
      { en: 'shy', gr: 'ντροπαλός', sentence: 'Ο Γιάννης είναι ντροπαλός με ξένους.', sentenceEn: 'Yiannis is shy around strangers.' },
      { en: 'determined', gr: 'αποφασισμένος', sentence: 'Η Μαρία είναι αποφασισμένη να τρέξει μαραθώνιο.', sentenceEn: 'Maria is determined to run a marathon.' },
      { en: 'overwhelmed', gr: 'συγκλονισμένος', sentence: 'Τόση δουλειά — νιώθω συγκλονισμένος.', sentenceEn: 'So much work — I feel overwhelmed.' },
      { en: 'impatient', gr: 'ανυπόμονος', sentence: 'Ο Κώστας είναι ανυπόμονος, δεν περιμένει.', sentenceEn: 'Kostas is impatient, he won\'t wait.' },
      { en: 'inspired', gr: 'εμπνευσμένος', sentence: 'Νιώθω εμπνευσμένος μετά τη συναυλία.', sentenceEn: 'I feel inspired after the concert.' },
      { en: 'indifferent', gr: 'αδιάφορος', sentence: 'Τον ρώτησα, αλλά ήταν τελείως αδιάφορος.', sentenceEn: 'I asked him, but he was totally indifferent.' },
      { en: 'terrified', gr: 'τρομοκρατημένος', sentence: 'Η Ελένη είναι τρομοκρατημένη από αράχνες.', sentenceEn: 'Eleni is terrified of spiders.' },
      { en: 'relieved', gr: 'ανακουφισμένος', sentence: 'Πέρασα τις εξετάσεις — τι ανακούφιση!', sentenceEn: 'I passed the exams — what a relief!' },
      { en: 'furious', gr: 'έξαλλος', sentence: 'Ο Νίκος ήταν έξαλλος με τον λογαριασμό.', sentenceEn: 'Nikos was furious about the bill.' },
      { en: 'moody', gr: 'κακόκεφος', sentence: 'Μην τον πειράζεις, είναι κακόκεφος.', sentenceEn: 'Don\'t tease him, he\'s moody.' },
    ],
  },
  {
    id: 'household',
    title: 'Σπίτι & Αντικείμενα',
    titleEn: 'Household nouns',
    icon: '🏠',
    words: [
      // Rooms & structure
      { en: 'room', gr: 'δωμάτιο', sentence: 'Αυτό το δωμάτιο θέλει βάψιμο.', sentenceEn: 'This room needs painting.' },
      { en: 'kitchen', gr: 'κουζίνα', sentence: 'Η κουζίνα μυρίζει σκόρδο και κανέλα.', sentenceEn: 'The kitchen smells of garlic and cinnamon.' },
      { en: 'bathroom', gr: 'μπάνιο', sentence: 'Το μπάνιο είναι κατειλημμένο — πάλι!', sentenceEn: 'The bathroom is occupied — again!' },
      { en: 'bedroom', gr: 'υπνοδωμάτιο', sentence: 'Ο Γιάννης κοιμάται ακόμα στο υπνοδωμάτιο.', sentenceEn: 'Yiannis is still sleeping in the bedroom.' },
      { en: 'living room', gr: 'σαλόνι', sentence: 'Ελάτε στο σαλόνι, αρχίζει η ταινία.', sentenceEn: 'Come to the living room, the movie\'s starting.' },
      { en: 'balcony', gr: 'μπαλκόνι', sentence: 'Η Ελένη πίνει καφέ στο μπαλκόνι.', sentenceEn: 'Eleni drinks coffee on the balcony.' },
      { en: 'stairs', gr: 'σκάλες', sentence: 'Ανεβαίνω τις σκάλες τρέχοντας.', sentenceEn: 'I run up the stairs.' },
      { en: 'floor', gr: 'πάτωμα', sentence: 'Ποιος λέρωσε το πάτωμα;', sentenceEn: 'Who dirtied the floor?' },
      { en: 'wall', gr: 'τοίχος', sentence: 'Ο Κώστας κρέμασε φωτογραφίες στον τοίχο.', sentenceEn: 'Kostas hung photos on the wall.' },
      { en: 'ceiling', gr: 'ταβάνι', sentence: 'Η αράχνη περπατάει στο ταβάνι.', sentenceEn: 'The spider is walking on the ceiling.' },
      { en: 'door', gr: 'πόρτα', sentence: 'Κλείσε την πόρτα, μπαίνει κρύο.', sentenceEn: 'Close the door, it\'s getting cold.' },
      { en: 'window', gr: 'παράθυρο', sentence: 'Άνοιξε το παράθυρο, κάνει ζέστη.', sentenceEn: 'Open the window, it\'s hot.' },
      // Living room
      { en: 'sofa', gr: 'καναπές', sentence: 'Ο Δημήτρης κοιμήθηκε στον καναπέ χτες.', sentenceEn: 'Dimitris fell asleep on the sofa yesterday.' },
      { en: 'table', gr: 'τραπέζι', sentence: 'Βάλε τα πιάτα στο τραπέζι.', sentenceEn: 'Put the plates on the table.' },
      { en: 'chair', gr: 'καρέκλα', sentence: 'Τράβηξε μια καρέκλα και κάτσε.', sentenceEn: 'Pull up a chair and sit down.' },
      { en: 'television', gr: 'τηλεόραση', sentence: 'Ο Νίκος βλέπει τηλεόραση όλη μέρα.', sentenceEn: 'Nikos watches television all day.' },
      { en: 'lamp', gr: 'λάμπα', sentence: 'Η λάμπα στο σαλόνι χάλασε.', sentenceEn: 'The living room lamp broke.' },
      { en: 'carpet', gr: 'χαλί', sentence: 'Η γάτα κοιμάται πάντα στο χαλί.', sentenceEn: 'The cat always sleeps on the carpet.' },
      { en: 'bookshelf', gr: 'βιβλιοθήκη', sentence: 'Η βιβλιοθήκη είναι γεμάτη, δεν χωράει άλλο.', sentenceEn: 'The bookshelf is full, nothing else fits.' },
      { en: 'curtains', gr: 'κουρτίνες', sentence: 'Τράβηξε τις κουρτίνες, μπαίνει ήλιος.', sentenceEn: 'Draw the curtains, the sun is coming in.' },
      // Kitchen
      { en: 'fridge', gr: 'ψυγείο', sentence: 'Ο Γιώργος άνοιξε το ψυγείο και ήταν άδειο.', sentenceEn: 'Giorgos opened the fridge and it was empty.' },
      { en: 'oven', gr: 'φούρνος', sentence: 'Πρόσεχε, ο φούρνος είναι ζεστός.', sentenceEn: 'Be careful, the oven is hot.' },
      { en: 'microwave', gr: 'φούρνος μικροκυμάτων', sentence: 'Ζέστανέ το στον φούρνο μικροκυμάτων.', sentenceEn: 'Heat it in the microwave.' },
      { en: 'sink', gr: 'νεροχύτης', sentence: 'Ο νεροχύτης είναι γεμάτος πιάτα.', sentenceEn: 'The sink is full of dishes.' },
      { en: 'plate', gr: 'πιάτο', sentence: 'Πρόσεχε, το πιάτο είναι ζεστό!', sentenceEn: 'Be careful, the plate is hot!' },
      { en: 'glass', gr: 'ποτήρι', sentence: 'Ο Γιάννης έσπασε ένα ποτήρι στην κουζίνα.', sentenceEn: 'Yiannis broke a glass in the kitchen.' },
      { en: 'fork', gr: 'πιρούνι', sentence: 'Δώσε μου ένα πιρούνι, παρακαλώ.', sentenceEn: 'Give me a fork, please.' },
      { en: 'knife', gr: 'μαχαίρι', sentence: 'Αυτό το μαχαίρι δεν κόβει καθόλου.', sentenceEn: 'This knife doesn\'t cut at all.' },
      { en: 'spoon', gr: 'κουτάλι', sentence: 'Χρειάζομαι κουτάλι για τη σούπα.', sentenceEn: 'I need a spoon for the soup.' },
      { en: 'pot', gr: 'κατσαρόλα', sentence: 'Η Μαρία έβαλε την κατσαρόλα στη φωτιά.', sentenceEn: 'Maria put the pot on the stove.' },
      { en: 'frying pan', gr: 'τηγάνι', sentence: 'Βάλε λάδι στο τηγάνι.', sentenceEn: 'Put oil in the frying pan.' },
      // Bedroom
      { en: 'bed', gr: 'κρεβάτι', sentence: 'Δεν θέλω να σηκωθώ από το κρεβάτι.', sentenceEn: 'I don\'t want to get out of bed.' },
      { en: 'pillow', gr: 'μαξιλάρι', sentence: 'Η Σοφία θέλει πάντα δύο μαξιλάρια.', sentenceEn: 'Sofia always wants two pillows.' },
      { en: 'blanket', gr: 'κουβέρτα', sentence: 'Φέρε μια κουβέρτα, κάνει κρύο.', sentenceEn: 'Bring a blanket, it\'s cold.' },
      { en: 'wardrobe', gr: 'ντουλάπα', sentence: 'Η ντουλάπα δεν κλείνει πια.', sentenceEn: 'The wardrobe won\'t close anymore.' },
      { en: 'alarm clock', gr: 'ξυπνητήρι', sentence: 'Ο Κώστας δεν άκουσε το ξυπνητήρι.', sentenceEn: 'Kostas didn\'t hear the alarm clock.' },
      { en: 'mirror', gr: 'καθρέφτης', sentence: 'Η Αθηνά κοιτάχτηκε στον καθρέφτη.', sentenceEn: 'Athina looked at herself in the mirror.' },
      // Bathroom
      { en: 'towel', gr: 'πετσέτα', sentence: 'Δώσε μου μια καθαρή πετσέτα.', sentenceEn: 'Give me a clean towel.' },
      { en: 'soap', gr: 'σαπούνι', sentence: 'Τελείωσε το σαπούνι, πάλι;', sentenceEn: 'The soap ran out, again?' },
      { en: 'shower', gr: 'ντους', sentence: 'Ο Δημήτρης κάνει ντους μετά το γυμναστήριο.', sentenceEn: 'Dimitris showers after the gym.' },
      { en: 'bathtub', gr: 'μπανιέρα', sentence: 'Η μπανιέρα είναι γεμάτη αφρό.', sentenceEn: 'The bathtub is full of bubbles.' },
      { en: 'toilet', gr: 'τουαλέτα', sentence: 'Συγγνώμη, πού είναι η τουαλέτα;', sentenceEn: 'Excuse me, where is the toilet?' },
      { en: 'toothbrush', gr: 'οδοντόβουρτσα', sentence: 'Ξέχασα την οδοντόβουρτσά μου στο σπίτι.', sentenceEn: 'I forgot my toothbrush at home.' },
      // Office
      { en: 'desk', gr: 'γραφείο', sentence: 'Το γραφείο του Νίκου είναι χάος.', sentenceEn: 'Nikos\'s desk is chaos.' },
      { en: 'computer', gr: 'υπολογιστής', sentence: 'Ο υπολογιστής κόλλησε πάλι.', sentenceEn: 'The computer froze again.' },
      { en: 'key', gr: 'κλειδί', sentence: 'Πού είναι τα κλειδιά;', sentenceEn: 'Where are the keys?' },
      { en: 'rubbish bin', gr: 'κάδος σκουπιδιών', sentence: 'Πέτα το στον κάδο, μυρίζει.', sentenceEn: 'Throw it in the bin, it smells.' },
      { en: 'washing machine', gr: 'πλυντήριο', sentence: 'Η Ελένη έβαλε πλυντήριο πριν φύγει.', sentenceEn: 'Eleni started the washing machine before leaving.' },
      { en: 'iron', gr: 'σίδερο', sentence: 'Ποιος σιδερώνει πια; Όχι εγώ.', sentenceEn: 'Who irons anymore? Not me.' },
    ],
  },
  {
    id: 'body-parts',
    title: 'Μέρη του σώματος',
    titleEn: 'Body parts',
    icon: '🦴',
    words: [
      { en: 'head', gr: 'κεφάλι', sentence: 'Με πονάει το κεφάλι μου.', sentenceEn: 'My head hurts.' },
      { en: 'face', gr: 'πρόσωπο', sentence: 'Το πρόσωπό του κοκκίνισε.', sentenceEn: 'His face turned red.' },
      { en: 'eye', gr: 'μάτι', sentence: 'Έχει πράσινα μάτια.', sentenceEn: 'She has green eyes.' },
      { en: 'ear', gr: 'αυτί', sentence: 'Ο σκύλος κουνάει τα αυτιά του.', sentenceEn: 'The dog is wagging his ears.' },
      { en: 'nose', gr: 'μύτη', sentence: 'Η μύτη μου είναι κρύα.', sentenceEn: 'My nose is cold.' },
      { en: 'mouth', gr: 'στόμα', sentence: 'Κλείσε το στόμα σου και φάε.', sentenceEn: 'Close your mouth and eat.' },
      { en: 'tooth', gr: 'δόντι', sentence: 'Με πονάει ένα δόντι.', sentenceEn: 'A tooth is hurting me.' },
      { en: 'neck', gr: 'λαιμός', sentence: 'Ο λαιμός μου πιάστηκε.', sentenceEn: 'My neck is stiff.' },
      { en: 'shoulder', gr: 'ώμος', sentence: 'Χτύπησα τον ώμο μου στην πόρτα.', sentenceEn: 'I hit my shoulder on the door.' },
      { en: 'arm', gr: 'μπράτσο', sentence: 'Σήκωσε τα μπράτσα σου ψηλά!', sentenceEn: 'Raise your arms high!' },
      { en: 'hand', gr: 'χέρι', sentence: 'Πλύνε τα χέρια σου πριν φας.', sentenceEn: 'Wash your hands before you eat.' },
      { en: 'finger', gr: 'δάχτυλο', sentence: 'Κόπηκα στο δάχτυλο.', sentenceEn: 'I cut my finger.' },
      { en: 'chest', gr: 'στήθος', sentence: 'Πονάει στο στήθος.', sentenceEn: 'His chest hurts.' },
      { en: 'back', gr: 'πλάτη', sentence: 'Η πλάτη μου με σκοτώνει.', sentenceEn: 'My back is killing me.' },
      { en: 'stomach', gr: 'στομάχι', sentence: 'Το στομάχι μου κάνει θόρυβο.', sentenceEn: 'My stomach is making noise.' },
      { en: 'leg', gr: 'πόδι', sentence: 'Τα πόδια μου κουράστηκαν από το περπάτημα.', sentenceEn: 'My legs are tired from walking.' },
      { en: 'knee', gr: 'γόνατο', sentence: 'Χτύπησα το γόνατό μου στο τραπέζι.', sentenceEn: 'I hit my knee on the table.' },
      { en: 'foot', gr: 'πατούσα', sentence: 'Πάτησα κάτι με τη γυμνή πατούσα.', sentenceEn: 'I stepped on something with my bare foot.' },
      { en: 'hair', gr: 'μαλλιά', sentence: 'Τα μαλλιά της είναι πολύ μακριά.', sentenceEn: 'Her hair is very long.' },
      { en: 'heart', gr: 'καρδιά', sentence: 'Η καρδιά μου χτυπάει γρήγορα.', sentenceEn: 'My heart is beating fast.' },
    ],
  },
];
